nelmio_api_doc:
    use_validation_groups: true
    documentation:
        info:
            title: WeAbove Community Api
            description: This is an API build by WeAbove community
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
